#!/bin/bash

# Location of RADMC-3D
RADMCDIR=$HOME/radmc3d

# Clone RADMC-3D
git clone https://github.com/dullemond/radmc3d-2.0.git $RADMCDIR

# Install RADMC-3D
cd $RADMCDIR/src
make

# Add directory with executable to PATH in .bashrc
echo "export PATH='$PATH:$RADMCDIR/src'" >> $HOME/.bashrc

# Install RADMC-3D Python module
cd $RADMCDIR/python/radmc3dPy
pip install .